# Site settings
title: "Marius Winkler"
description: "Atmospheric physicist"
url: "https://mariuswinkler.github.io"  # replace with custom domain if needed
baseurl: ""  # keep empty for user sites

# Use the Minimal Mistakes remote theme
remote_theme: "mmistakes/minimal-mistakes"

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Author
author:
  name: "Marius Winkler"
  avatar: "/assets/images/avatar.png"
  bio: "Postdoc, atmospheric physicist."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mariuswinkler"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/marius-winkler-2828121b4/"
    - label: "Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=jUrnxisAAAAJ&hl=en"

# Layout defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      toc: true

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

include:
  - assets/css

