# Site settings
title: "Marius Winkler"
description: "Physicist"
url: "https://mariuswinkler.github.io"  
baseurl: ""  # keep empty for user sites

# Use the Minimal Mistakes remote theme
remote_theme: "mmistakes/minimal-mistakes"

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Author
author:
  name: "Marius Winkler"
  avatar: "/assets/images/MW.jpeg"
  bio: "Physicist"
  links:
    - label: "Max Planck Institute for Meteorology"
      icon: "fas fa-map-marker-alt"
      url: "https://mpimet.mpg.de"
    - label: "Hamburg, Germany"
      icon: "fas fa-map-pin"
      url: ""
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:marius.winkler@mpimet.mpg.de"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mariuswinkler"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/marius-winkler-2828121b4/"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.de/citations?user=jUrnxisAAAAJ&hl=de&oi=ao"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0002-1280-292X"


# Layout defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      toc: false
      custom_head: head_custom

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

include:
  - assets/css
  - _pages

navigation: 
  enabled: true


