title: "Marius Winkler"
email: "marius.winkler@mpimet.mpg.de"
description: "Atmospheric physicist, currently engaged as a Postdoc at the Max Planck Institute for Meteorology, Hamburg."
baseurl: "" 
url: "https://mariuswinkler.github.io" # or your custom domain

locale: "en"
repository: "mariuswinkler/mariuswinkler.github.io"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # or "air", "contrast", etc.

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives


author:
  name: "Marius Winkler"
  avatar: "/assets/images/avatar.png" # optional
  bio: "Postdoc, atmospheric physicist."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mariuswinkler"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/marius-winkler-2828121b4/"
    - label: "Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=jUrnxisAAAAJ&hl=en"

# Navigation
header_pages:
  - _pages/der_rote_faden.md
  - _pages/research.md
  - _pages/vita.md
  - _pages/publications_and_conferences.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Build settings
markdown: kramdown
highlighter: rouge


sass:
  style: compressed

include:
  - assets/css
